//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocion
    {
        public int PromocionID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public decimal PrecioPromocion { get; set; }
        public string Imagen { get; set; }
        public int ProductoID { get; set; }
        public string UrlImagen { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
